//ActionTypes.js

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const GET_USERS_ORDERS_REQUEST = 'GET_USERS_ORDERS_REQUEST';
export const GET_USERS_ORDERS_SUCCESS = 'GET_USERS_ORDERS_SUCCESS';
export const GET_USERS_ORDERS_FAILURE = 'GET_USERS_ORDERS_FAILURE';

/* We havn't implements notification API as of now */
export const GET_USERS_NOTIFICATION_REQUEST = 'GET_USERS_NOTIFICATION_REQUEST';
export const GET_USERS_NOTIFICATION_SUCCESS = 'GET_USERS_NOTIFICATION_SUCCESS';
export const GET_USERS_NOTIFICATION_FAILURE = 'GET_USERS_NOTIFICATION_FAILURE';


export const CREATE_ADDRESS_REQUEST="CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_SUCCESS="CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_FAILURE="CREATE_ADDRESS_FAILURE";

export const GET_ALL_ADDRESS_REQUEST="GET_ALL_ADDRESS_REQUEST";
export const GET_ALL_ADDRESS_SUCCESS="GET_ALL_ADDRESS_SUCCESS";
export const GET_ALL_ADDRESS_FAILURE="GET_ALL_ADDRESS_FAILURE";

export const DELETE_ADDRESS_REQUEST="DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS="DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE="DELETE_ADDRESS_FAILURE";

export const UPDATE_ADDRESS_REQUEST="UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS="UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE="UPDATE_ADDRESS_FAILURE";

export const GET_ADDRESS_BY_ID_REQUEST="GET_ADDRESS_BY_ID_REQUEST";
export const GET_ADDRESS_BY_ID_SUCCESS="GET_ADDRESS_BY_ID_SUCCESS";
export const GET_ADDRESS_BY_ID_FAILURE="GET_ADDRESS_BY_ID_FAILURE";