export const GET_RESTAURANTS_ORDER_REQUEST = 'GET_RESTAURANTS_ORDER_REQUEST';
export const GET_RESTAURANTS_ORDER_SUCCESS = 'GET_RESTAURANTS_ORDER_SUCCESS';
export const GET_RESTAURANTS_ORDER_FAILURE = 'GET_RESTAURANTS_ORDER_FAILURE';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';

export const DELETE_ORDERS_REQUEST='DELETE_ORDERS_REQUEST'; 
export const DELETE_ORDERS_SUCCESS='DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FAILURE='DELETE_ORDERS_FAILURE';

export const GET_ALL_ORDER_REQUEST="GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS="GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAILURE="GET_ALL_ORDER_FAILURE";
